name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: New changes 
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 54.241.225.20
        username: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
            cd /usr/share/nginx/CI-CD-DEMO
            sudo git pull
            sudo nginx -s reload
